OrangeTech.Web/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using OrangeTech.BLL.Interfaces;
using OrangeTech.Models.Models;
using OrangeTech.Web.ViewModels;
using ReflectionIT.Mvc.Paging;

namespace OrangeTech.Web.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IServiceService _serviceService;

        public ServiceController(IServiceService serviceService, IMapper mapper)
        {
            _serviceService = serviceService;
            _mapper = mapper;
        }

        [HttpGet("services")]
        public IActionResult GetAll(int page = 1)
        {
            var serviceShortViewModel = _mapper.Map<IEnumerable<Service>, IEnumerable<ServiceShortViewModel>>(_serviceService.GetAll());
            var model = PagingList.Create(serviceShortViewModel, 5, page);
            return View(model);
        }

        [HttpPost("services/add")]
        public IActionResult Create(ServiceViewModel serviceViewModel)
        {
            if (serviceViewModel.Images.Count < 5 && serviceViewModel.Images.Count > 0)
            {
                var service = _mapper.Map<ServiceViewModel, Service>(serviceViewModel);
                _serviceService.Create(service);
                return RedirectToAction("GetAll");
            }

            return View(serviceViewModel);
        }

        [HttpGet("services/add")]
        public IActionResult Create()
        {
            if (User.IsInRole("Admin"))
            {
                return View();
            }

            return RedirectToAction("Login", "Account", "");
        }

        [HttpGet("services/remove")]
        public IActionResult Remove(Guid serviceId)
        {

            if (User.IsInRole("Admin"))
            {
                _serviceService.Delete(serviceId);
                return RedirectToAction("GetAll");
            }

            return RedirectToAction("Login", "Account", "");
        }

        [HttpGet("services/{serviceId}/details")]
        public IActionResult Details(Guid serviceId)
        {
            var service = _serviceService.GetById(serviceId);
            return View(service);
        }
    }
}

OrangeTech.Web/Controllers/WorkController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrangeTech.BLL.Interfaces;
using OrangeTech.Models.Models;
using OrangeTech.Web.ViewModels;
using ReflectionIT.Mvc.Paging;
using System;
using System.Collections.Generic;

namespace OrangeTech.Web.Controllers
{
    public class WorkController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IWorkService _workService;

        public WorkController(IWorkService workService, IMapper mapper)
        {
            _workService = workService;
            _mapper = mapper;
        }

        [HttpGet("works")]
        public IActionResult GetAll(int page = 1)
        {
            var worksViewModels = _mapper.Map<IEnumerable<Work>, IEnumerable<WorkShortViewModel>>(_workService.GetAll());
            var model = PagingList.Create(worksViewModels, 5, page);
            return View(model);            
        }

        [HttpPost("works/add")]
        public IActionResult Create(WorkViewModel workViewModel)
        {
            if (workViewModel.Images.Count < 5 && workViewModel.Images.Count > 0)
            {
                var work = _mapper.Map<WorkViewModel, Work>(workViewModel);
                _workService.Create(work);
                return RedirectToAction("GetAll");
            }

            return View(workViewModel);
        }

        [HttpGet("works/add")]
        public IActionResult Create()
        {
            if (User.IsInRole("Admin"))
            {
                return View();
            }

            return RedirectToAction("Login", "Account", "");
        }

        [HttpGet("works/remove")]
        public IActionResult Remove(Guid workId)
        {

            if (User.IsInRole("Admin"))
            {
                _workService.Delete(workId);
                return RedirectToAction("GetAll");
            }

            return RedirectToAction("Login", "Account", "");
        }

        [HttpGet("works/{workId}/details")]
        public IActionResult Details(Guid workId)
        {
            var work = _workService.GetById(workId);
            return View(work);
        }
    }
}

OrangeTech.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrangeTech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <title>ORANGETECH</title>
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/header.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="~/img/icon.jpg">
    <script src="https://unpkg.com/js-image-zoom@0.4.1/js-image-zoom.js" type="application/javascript"></script>
</head>
<body>
    <header>
        <div class="header">
            <div class="conteiner">
                <div class="row">
                    <div class="header-content-left">
                        <div class="header-icon">
                            <a id="logo" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/img/logo-icon.jpg" class="image-icon">
                            </a>
                        </div>

                    </div>

                    <div class="header-content-right">
                        <div class="content-right">
                            <div class="contact">
                                <div class="contacts-list">
                                    <ul>
                                        <li class="phone">
                                            <a class="phonelink" href="tel:+380(95)2478205">
                                                <span itemprop="telephone">
                                                    <span>+380 (95) 247 8205</span>
                                                </span>
                                            </a>

                                        </li>
                                        <li class="adress">
                                            <span>г. Харьков, ул. Борщаговская, 154</span>
                                        </li>
                                        <li class="post">
                                            <span>orangetech@gmail.com</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="mainmenu">
                            <nav class="nav">
                                <a class="nav__link"  asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                                <a class="nav__link" href="#about">О нас</a>
                                <a class="nav__link" asp-area="" asp-controller="Service" asp-action="GetAll">Услуги</a>
                                <a class="nav__link" asp-area="" asp-controller="Work" asp-action="GetAll">Наши работы</a>
                                <a class="nav__link" href="#">Контакты</a>
                                @Html.Partial("_LoginPartial")
                            </nav>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        </nav>
    </header>    
    <main>
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

OrangeTech.Web/Views/Shared/_ServicePagination.cshtml
@model ReflectionIT.Mvc.Paging.IPagingList


@{
    var start = this.Model.StartPageIndex;
    var stop = this.Model.StopPageIndex;
}


<br />
@if (this.Model.PageCount > 1)
{
    <ul class="pager">

        @if (start > 1)
        {
            <li class="pager-item">
                <a class="pager-link active-page" asp-route-page="1" asp-controller="Service" asp-action="GetAll" aria-label="First" onclick="filter(1)"><span aria-hidden="true">1</span></a>
            </li>
        }

        @if (this.Model.PageIndex > 1)
        {
            <li class="pager-item">
                <a class="pager-link active-page" aria-label="Previous" asp-route-page="@(Model.PageIndex - 1)" asp-controller="Service" asp-action="GetAll"><span aria-hidden="true">&laquo;</span></a>
            </li>
        }

        @for (int i = start; i <= stop; i++)
        {
            <li class="pager-item @((Model.PageIndex == i) ? "active" : null)">
                <a class="pager-link active-page" , asp-route-page="@i" asp-controller="Service" asp-action="GetAll">@i</a>
            </li>
        }

        @if (this.Model.PageIndex < this.Model.PageCount)
        {
            <li class="pager-item">
                <a class="pager-link active-page" aria-label="Next" asp-route-page="@(Model.PageIndex + 1)" asp-controller="Service" asp-action="GetAll"><span aria-hidden="true">&raquo;</span></a>
            </li>
        }

        @if (stop < this.Model.PageCount)
        {
            <li class="pager-item">
                <a class="pager-link active-page" aria-label="Last" asp-route-page="@Model.PageCount" asp-controller="Service" asp-action="GetAll"><span aria-hidden="true">@this.Model.PageCount</span></a>
            </li>
        }

    </ul>
}
<link href="~/css/pagination.css" rel="stylesheet" />

OrangeTech.Web/Views/Shared/_WorkPagination.cshtml
@model ReflectionIT.Mvc.Paging.IPagingList


@{
    var start = this.Model.StartPageIndex;
    var stop = this.Model.StopPageIndex;
}


<br />
@if (this.Model.PageCount > 1)
{
    <ul class="pager">

        @if (start > 1)
        {
            <li class="pager-item">
                <a class="pager-link active-page" asp-route-page="1" asp-controller="Work" asp-action="GetAll" aria-label="First" onclick="filter(1)"><span aria-hidden="true">1</span></a>
            </li>
        }

        @if (this.Model.PageIndex > 1)
        {
            <li class="pager-item">
                <a class="pager-link active-page" aria-label="Previous" asp-route-page="@(Model.PageIndex - 1)" asp-controller="Work" asp-action="GetAll"><span aria-hidden="true">&laquo;</span></a>
            </li>
        }

        @for (int i = start; i <= stop; i++)
        {
            <li class="pager-item @((Model.PageIndex == i) ? "active" : null)">
                <a class="pager-link active-page" , asp-route-page="@i" asp-controller="Work" asp-action="GetAll">@i</a>
            </li>
        }

        @if (this.Model.PageIndex < this.Model.PageCount)
        {
            <li class="pager-item">
                <a class="pager-link active-page" aria-label="Next" asp-route-page="@(Model.PageIndex + 1)" asp-controller="Work" asp-action="GetAll"><span aria-hidden="true">&raquo;</span></a>
            </li>
        }

        @if (stop < this.Model.PageCount)
        {
            <li class="pager-item">
                <a class="pager-link active-page" aria-label="Last" asp-route-page="@Model.PageCount" asp-controller="Work" asp-action="GetAll"><span aria-hidden="true">@this.Model.PageCount</span></a>
            </li>
        }

    </ul>
}
<link href="~/css/pagination.css" rel="stylesheet" />